import type { JsonValue } from './json';
import type { MatchClockStatus } from './enums';

/**
 * Distinct from per-phase timers (PhaseInfo). Deadline-based, not a client-decremented counter —
 * see GAMEPLAY_RULES_V1.md §6. `MatchClockService` (apps/server/src/timers/match-clock-service.ts)
 * is the only thing that schedules real time against `deadlineAt`; everything else treats this as
 * a plain data snapshot.
 */
export interface MatchClock {
  status: MatchClockStatus;
  /**
   * Regenerated every time the clock (re)starts running (initial start, and every resume after a
   * special-game pause) — a staleness guard for scheduled expiry callbacks, playing the same role
   * `PhaseInfo.phaseId` plays for phase timers. Never regenerated by a pause.
   */
  clockId: string;
  /** Epoch ms — the moment investigation gameplay began. Null before that. */
  startedAt: number | null;
  /** Authoritative epoch ms deadline while `status === 'running'`; null otherwise. */
  deadlineAt: number | null;
  /**
   * Authoritative "time left," in ms. The source of truth while paused/pending/stopped; while
   * running, the live remaining time is always `deadlineAt - now()`, never read from this field.
   */
  remainingMs: number;
  /** Cumulative special-game failure penalty applied so far, for display/audit only. */
  totalPenaltyMs: number;
}

export interface MatchLogEntry {
  at: number;
  type: 'penalty_applied' | 'firewall_activated' | 'firewall_consumed' | 'special_game_result' | 'hack_accepted' | 'match_clock_expired' | string;
  detail: JsonValue;
}
